version: '3'

services:
  postgres:
    image: postgres:17.0
    container_name: postgres_container
    restart: always

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3E7Z@"Z8%itC

    volumes:
      - /postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: asitsonawanework@gmail.com
      PGADMIN_DEFAULT_PASSWORD: AiC7!49"Wv
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgadmin-data:
  postgres_data: